from _typeshed import Incomplete
from collections.abc import Iterable

def subdict(d, keys): ...
def upsert_reranker_model(model_name: str = 'cross-encoder/ms-marco-MiniLM-L-6-v2', device: str = 'cuda', **kwargs): ...
def rerank(universe: Iterable[str], query: str, cross_encoder: Incomplete | None = None, include: Iterable[str] | None = None, *args, **kwargs): ...
